baseURL: "https://tonton-520.github.io/"
locale: zh
title: "刘彤 - AI 产品经理"

module:
  imports:
    - path: "github.com/hugo-toha/toha/v4"

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  gitRepo: "https://github.com/tonton-520/personal-website"
  gitBranch: "main"

  features:
    theme:
      enable: true
      services:
        light: true
        dark: true
        default: light

  topNavbar:
    maxVisibleSections: 5

  footer:
    enable: true

  featuresDarkMode: true
